# ALTER TABLE `authorities` ADD COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
# ALTER TABLE `authorities` ADD COLUMN `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
# ALTER TABLE `authorities` ADD COLUMN `created_by` VARCHAR(36) NOT NULL;
# ALTER TABLE `authorities` ADD COLUMN `disabled` BOOLEAN NOT NULL DEFAULT FALSE;
# # ALTER TABLE `authorities` ADD CONSTRAINT `fk_authorities_created_by` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`);